### PR TITLE
Akshay bodhare patch 1

### PR DESCRIPTION
**Pull request by AkshayBodhare**

### CODE REVIEW

**Comment by AkshayBodhare** [comment]
Did some rudimentary extraction of sentences and created a list of venues

**Comment by gurbir-a** [comment]
send a PR for a branch other than master

**Comment by gurbir-a** [comment]
What are the two files?
`venues.json` and `venues_updates.json`

**Comment by AkshayBodhare** [comment]
It has venues in different formats
I have written a short extract script
use it to see the data stored in the two json files

**Comment by gurbir-a** [comment]
but why?
and also, open a new PR for a different branch

**Pull request closed without merging**
